FROM ${docker.baseimage}

# Set the environment variables
ENV VERTICLE_FILE ${build.finalName}.jar
ENV VERTICLE_NAME nl.webprint.Standalone
ENV VERTICLE_HOME /usr/verticles

EXPOSE 8181

# Copy your fat jar to the container
COPY maven/${VERTICLE_FILE} $VERTICLE_HOME/

# Launch the verticle
WORKDIR $VERTICLE_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec vertx run $VERTICLE_NAME -cp $VERTICLE_HOME/*"]